'''
Pseudo synchronous imprint thread should respond to imprint commands in a timely
manner:
    
    - Policy network back prop from imprint command.
    
    - Policy network back from from every N gradients generated by V*.
'''