'''
Pseudo synchronous imprint thread should respond to imprint commands in a timely
manner:
    
    - Policy network back prop from imprint command.
    
    - Policy network back from from every N gradients generated by V*.
'''

# Imports 
import multiprocessing


class ImprintProcess(multiprocessing.Process):

    def __init__(self, _args):
        
        # init name
        self.process_name = "Imprint Process"
        
        # call super init
        super(ImprintProcess, self).__init__(name=self.process_name, args=_args)

    def run(self, *args):
        return